# Generated by Django 5.1.6 on 2025-03-16 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_remove_user_groups_remove_user_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="currency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="finance.currency",
            ),
        ),
    ]
